---
name: Semantic Release

on:
  push:
    branches:
      - "*"

env:
  GH_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        psr-version: ["8.7.0", "9.16.1"]
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Debug GITHUB_ACTION
      run: |
        echo "GITHUB_ACTION is $GITHUB_ACTION"
    - name: Python Semantic Release
      id: release
      uses: zckv/python-semantic-release-composite-action@dev
      with:
        changelog: false
        github_token: ${{ secrets.PAT_TOKEN }}
        root_options: -v
        psr_version:  ${{ matrix.psr-version }}
        commit: true
        push: ${{ matrix.psr-version == '8.7.2' }}
    - name: Add file to check if it is added
      env: 
        tag: ${{ steps.release.outputs.tag }}
        released: ${{ steps.release.outputs.released }}
        version: ${{ steps.release.outputs.version }}
      run: mkdir -p dist && echo "Hello World !" >> dist/hello.txt
    - name: Debug GITHUB_ACTION
      run: |
        ls -la
        echo "test_variable=test" >> $GITHUB_ACTION
        ls -la
        echo "Content of $GITHUB_ACTION file:"
        cat "$GITHUB_ACTION"
        echo "Debug EOF"
    - name: Publish package to GitHub Release
      uses: python-semantic-release/upload-to-gh-release@main
      if: steps.release.outputs.released
      with:
        github_token: ${{ secrets.PAT_TOKEN }}
        tag: ${{ steps.release.outputs.tag }}
        root_options: -vv
