---
name: Semantic Release

on:
  push:
    branches:
      - "*"

env:
  GH_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Python Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@v8.0.8
      # uses: zckv/python-semantic-release@switch_to_a_composite_action
      with:
        changelog: false
        github_token: ${{ secrets.PAT_TOKEN }}
        root_options: -v
    - name: Add file to check if it is added
      env: 
        tag: ${{ steps.release.outputs.tag }}
        released: ${{ steps.release.outputs.released }}
        version: ${{ steps.release.outputs.version }}
      run: echo "Hello World !" >> dist/hello.txt
    - name: Publish package to GitHub Release
      uses: python-semantic-release/upload-to-gh-release@main
      if: steps.release.outputs.released
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.release.outputs.tag }}
        root_options: -vv
